services:
    paper_type.manager:
        class: SoulDock\PaperBundle\Service\SoulDockBaseEntityManager
        arguments: ["@doctrine.orm.entity_manager", 'SoulDockPaperBundle:PaperType']

    paper.manager:
        class: SoulDock\PaperBundle\Service\PaperManager
        arguments: ["@doctrine.orm.entity_manager", 'SoulDockPaperBundle:Paper']

