<?php

namespace AppBundle\Repository;

/**
 * PaperTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
