soul_dock_survey:
    resource: "@SoulDockSurveyBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

soul_dock_rest:
    resource: "@SoulDockRestBundle/Resources/config/routing.yml"
    prefix:   /

soul_dock_user:
    type: rest
    prefix: /api
    resource: "@SoulDockUserBundle/Resources/config/routing.yml"

soul_dock_web:
    resource: "@SoulDockWebBundle/Resources/config/routing.yml"
    prefix:   /

soul_dock_paper:
    type: rest
    prefix: /api
    resource: "@SoulDockPaperBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"