soul_dock_rest:
    resource: "@SoulDockRestBundle/Resources/config/routing.yml"
    prefix:   /

soul_dock_user:
    resource: "@SoulDockUserBundle/Resources/config/routing.yml"
    prefix:   /

soul_dock_web:
    resource: "@SoulDockWebBundle/Resources/config/routing.yml"
    prefix:   /

soul_dock_paper:
    type: rest
    prefix: /api
    resource: "@SoulDockPaperBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc