app_rest_register:
    type: rest
    prefix: /v1
    resource: "@SoulDockUserBundle/Controller/RegisterRestController.php"
    name_prefix:  api_1_

app_rest_user:
    type: rest
    prefix: /v1
    resource: "@SoulDockUserBundle/Controller/UserRestController.php"
    name_prefix:  api_1_