services:
    soul_dock.user.mailer.twig_swift:
        class: SoulDock\UserBundle\Mailer\UserMailer
        public: false
        arguments:
            - '@mailer'
            - '@router'
            - '@twig'
            -
                from_email:
                    confirmation: "%fos_user.registration.confirmation.from_email%"
                    resetting: "%fos_user.resetting.email.from_email%"
                template:
                    confirmation: "%fos_user.registration.confirmation.template%"
                    resetting: "%fos_user.resetting.email.template%"
                url:
                    confirmation: "%user_url_confirmation%"
                    resetting: "%user_url_resetting%"