<?php

namespace SoulDock\TagBundle\Repository;

/**
 * TaggedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaggedEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
