<?php

namespace SoulDock\PaperBundle\Repository;

/**
 * PaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperRepository extends \Doctrine\ORM\EntityRepository
{
}
