<?php

namespace SoulDock\PaperBundle\Repository;

/**
 * PaperTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTranslated($id, $language) {
        $qb = $this->createQueryBuilder('pt');

        $qb->where('pt.id = :id');
        $qb->setParameter('id', $id);

        $query = $qb->getQuery();

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $language
        );

        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
            1
        );

        $result = $query->getResult();

        if ($result) {
            $paperType = $result[0];
        }
        else {
            $paperType = null;
        }

        return $paperType;
    }
}
